config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "converters#index"
  post "/converted", to: "converters#show", as: "converted"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/converters_controller.rb
class ConvertersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index; end

  def show
    @answer = decimal_to_binary(params[:Number].to_i, params[:Base].to_i)
  end

  def decimal_to_binary(decimal, base = 2)
    arr = []
    until decimal.zero?
      number = decimal % base
      arr << number
      decimal /= base
    end
    arr.length.zero? ? "0" : hash(arr).reverse.join
  end

  def hash(arr)
    hash = { A: 10, B: 11, C: 12, D: 13, E: 14, F: 15 }

    arr.each_with_index do |number, index|
      hash.each do |key, value|
        arr[index] = key.to_s if number == value
      end
    end
    arr
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converters_helper.rb
module ConvertersHelper
end

app/views/converters/index.html.erb
<h1>Convert Decimal Numbers Into Any Base</h1>
<div>
<form action="<%= converted_path %>" method="POST">
<input type="number" name="Number" placeholder="Decimal Number">
<input type="number" name="Base" placeholder="Base number">
<button>Convert It!!!</button>
</form>
</div>

app/views/converters/show.html.erb
<body class="show">
<h1 class="answer"><%= @answer %></h1>
</body>
<footer>
<%= link_to 'Back', root_path %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseConverter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>